/*
    Copyright 2020-2023. Huawei Technologies Co., Ltd. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License")
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

const HAEventType = {
  CREATEPAYMENTINFO: "$CreatePaymentInfo",
  ADDPRODUCT2CART: "$AddProduct2Cart",
  ADDPRODUCT2WISHLIST: "$AddProduct2WishList",
  STARTAPP: "$StartApp",
  STARTCHECKOUT: "$StartCheckout",
  VIEWCAMPAIGN: "$ViewCampaign",
  VIEWCHECKOUTSTEP: "$ViewCheckoutStep",
  WINVIRTUALCOIN: "$WinVirtualCoin",
  COMPLETEPURCHASE: "$CompletePurchase",
  OBTAINLEADS: "$ObtainLeads",
  JOINUSERGROUP: "$JoinUserGroup",
  COMPLETELEVEL: "$CompleteLevel",
  STARTLEVEL: "$StartLevel",
  UPGRADELEVEL: "$UpgradeLevel",
  SIGNIN: "$SignIn",
  SIGNOUT: "$SignOut",
  SUBMITSCORE: "$SubmitScore",
  CREATEORDER: "$CreateOrder",
  REFUNDORDER: "$RefundOrder",
  DELPRODUCTFROMCART: "$DelProductFromCart",
  SEARCH: "$Search",
  VIEWCONTENT: "$ViewContent",
  UPDATECHECKOUTOPTION: "$UpdateCheckoutOption",
  SHARECONTENT: "$ShareContent",
  REGISTERACCOUNT: "$RegisterAccount",
  CONSUMEVIRTUALCOIN: "$ConsumeVirtualCoin",
  STARTTUTORIAL: "$StartTutorial",
  COMPLETETUTORIAL: "$CompleteTutorial",
  OBTAINACHIEVEMENT: "$ObtainAchievement",
  VIEWPRODUCT: "$ViewProduct",
  VIEWPRODUCTLIST: "$ViewProductList",
  VIEWSEARCHRESULT: "$ViewSearchResult",
  UPDATEMEMBERSHIPLEVEL: "$UpdateMembershipLevel",
  FILTRATEPRODUCT: "$FiltrateProduct",
  VIEWCATEGORY: "$ViewCategory",
  UPDATEORDER: "$UpdateOrder",
  CANCELORDER: "$CancelOrder",
  COMPLETEORDER: "$CompleteOrder",
  CANCELCHECKOUT: "$CancelCheckout",
  OBTAINVOUCHER: "$ObtainVoucher",
  CONTACTCUSTOMSERVICE: "$ContactCustomService",
  RATE: "$Rate",
  INVITE: "$Invite",
  NOVICEGUIDESTART: "$NoviceGuideStart",
  NOVICEGUIDEEND: "$NoviceGuideEnd",
  STARTGAME: "$StartGame",
  ENDGAME: "$EndGame",
  WINPROPS: "$WinProps",
  CONSUMEPROPS: "$ConsumeProps",
  ADDFRIEND: "$AddFriend",
  ADDBLACKLIST: "$AddBlacklist",
  VIEWFRIENDLIST: "$ViewFriendList",
  QUITUSERGROUP: "$QuitUserGroup",
  CREATEUSERGROUP: "$CreateUserGroup",
  DISBANDUSERGROUP: "$DisbandUserGroup",
  UPGRADEUSERGROUP: "$UpgradeUserGroup",
  VIEWUSERGROUP: "$ViewUserGroup",
  JOINTEAM: "$JoinTeam",
  SENDMESSAGE: "$SendMessage",
  LEARNSKILL: "$LearnSkill",
  USESKILL: "$UseSkill",
  GETEQUIPMENT: "$GetEquipment",
  LOSEEQUIPMENT: "$LoseEquipment",
  ENHANCEEQUIPMENT: "$EnhanceEquipment",
  SWITCHCLASS: "$SwitchClass",
  ACCEPTTASK: "$AcceptTask",
  FINISHTASK: "$FinishTask",
  ATTENDACTIVITY: "$AttendActivity",
  FINISHCUTSCENE: "$FinishCutscene",
  SKIPCUTSCENE: "$SkipCutscene",
  GETPET: "$GetPet",
  LOSEPET: "$LosePet",
  ENHANCEPET: "$EnhancePet",
  GETMOUNT: "$GetMount",
  LOSEMOUNT: "$LoseMount",
  ENHANCEMOUNT: "$EnhanceMount",
  CREATEROLE: "$CreateRole",
  SIGNINROLE: "$SignInRole",
  SIGNOUTROLE: "$SignOutRole",
  STARTBATTLE: "$StartBattle",
  ENDBATTLE: "$EndBattle",
  STARTDUNGEON: "$StartDungeon",
  FINISHDUNGEON: "$FinishDungeon",
  VIEWPACKAGE: "$ViewPackage",
  REDEEM: "$Redeem",
  MODIFYSETTING: "$ModifySetting",
  WATCHVIDEO: "$WatchVideo",
  CLICKMESSAGE: "$ClickMessage",
  DRAWCARD: "$DrawCard",
  VIEWCARDLIST: "$ViewCardList",
  BINDACCOUNT: "$BindAccount",
  STARTEXERCISE: "$StartExercise",
  ENDEXERCISE: "$EndExercise",
  STARTPLAYMEDIA: "$StartPlayMedia",
  ENDPLAYMEDIA: "$EndPlayMedia",
  STARTEXAMINE: "$StartExamine",
  ENDEXAMINE: "$EndExamine",
  CHECKIN: "$CheckIn",
  COMPENSATION: "$Compensation",
  POST: "$Post",
  SHAREAPP: "$ShareApp",
  IMPROVEINFORMATION: "$ImproveInformation",
  EXCHANGEGOODS: "$ExchangeGoods",
  VIEWHOUSELIST: "$ViewHouseList",
  VIEWHOUSEDETAIL: "$ViewHouseDetail",
  BINDDEVICE: "$BindDevice",
  UNBINDDEVICE: "$UnBindDevice",
  RESERVEMAINTENANCE: "$ReserceMaintenance",
  DEVICEMISSINGREPORT: "$DeviceMissingReport",
  STARTBOOKING: "$StartBooking",
  LEARNTARGET: "$LearnTarget",
  LANGUAGETEST: "$LanguageTest",
  STARTTRAINING: "$StartTraining",
  ENDTRAINING: "$EndTraining",
  REGISTERACTIVITY: "$RegisterActivity",
  EXITACTIVITY: "$ExitActivity",
  COMPLETEACTIVITY: "$CompleteActivity",
  ENTERACCOUNTOPENING: "$EnterAccountOpening",
  SUBMITACCOUNTOPENING: "$SubmitAccountOpening",
  BANDCARD: "$BandCard",
  BANKTRANSFERIN: "$BankTransferIn",
  BANKTRANSFEROUT: "$BankTransferOut",
  VIEWSTOCKDETAIL: "$ViewStockDetail",
  TRADESTOCKS: "$TradeStocks",
  VIEWFINANCEPAGE: "$ViewFinancePage",
  PURCHASEFINANCE: "$PurchaseFinance",
  REDEMPTIONFINANCE: "$RedemptionFinance",
  FUNDTRADING: "$FundTrading",
  FIXEDINVESTMENT: "$Fixedinvestment",
  APPLYNEW: "$ApplyNew",
  VIEWINFORMATIONSECTION: "$ViewInformationSection",
  VIEWINFORMATION: "$ViewInformation",
  MODULARCLICK: "$ModularClick",
  PAGEVIEW: "$PageView",
  DISPLAYVOUCHER: "$DisplayVoucher",
  BOOKCOURSE: "$BookCourse",
  LEARNCOURSES: "$LearnCourses",
  TRYOUT: "$Tryout",
  ANSWER: "$Answer",
  COMMENTCONTENT: "$CommentContent",
  LIKECONTENT: "$LikeContent",
  DELETEPRODUCT2WISHLIST: "$DeleteProduct2WishList",
  ADCLICK: "$AdClick",
  ADDISPLAY: "$AdDisplay",
  ENABLEMEMBER: "$EnableMember",
  CANCELMEMBER: "$CancelMember",
  CLICKPURCHASE: "$ClickPurchase",
  VIEWFUNDPAGE: "$ViewFundPage",
  VIPCLICK: "$vipClick",
  VIPFAILED: "$vipFailed",
  VIPSUC: "$vipSuc",
  REGISTERFAILED: "$registerFailed",
  PERMISSIONAPPLICATION: "$permissionApplication",
};

Object.freeze(HAEventType);
export default HAEventType;
