/*
    Copyright 2020-2021. Huawei Technologies Co., Ltd. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License")
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

const HAParamType = {
  STORENAME: "$StoreName",
  BRAND: "$Brand",
  CATEGORY: "$Category",
  PRODUCTID: "$ProductId",
  PRODUCTNAME: "$ProductName",
  PRODUCTFEATURE: "$ProductFeature",
  PRICE: "$Price",
  QUANTITY: "$Quantity",
  REVENUE: "$Revenue",
  CURRNAME: "$CurrName",
  PLACEID: "$PlaceId",
  DESTINATION: "$Destination",
  ENDDATE: "$EndDate",
  BOOKINGDAYS: "$BookingDays",
  PASSENGERSNUMBER: "$PassengersNumber",
  BOOKINGROOMS: "$BookingRooms",
  ORIGINATINGPLACE: "$OriginatingPlace",
  BEGINDATE: "$BeginDate",
  TRANSACTIONID: "$TransactionId",
  CLASS: "$Class",
  CLICKID: "$ClickId",
  PROMOTIONNAME: "$PromotionName",
  CONTENT: "$Content",
  EXTENDPARAM: "$ExtendParam",
  MATERIALNAME: "$MaterialName",
  MATERIALSLOT: "$MaterialSlot",
  MEDIUM: "$Medium",
  SOURCE: "$Source",
  KEYWORDS: "$Keywords",
  OPTION: "$Option",
  STEP: "$Step",
  VIRTUALCURRNAME: "$VirtualCurrName",
  VOUCHER: "$Voucher",
  PLACE: "$Place",
  SHIPPING: "$Shipping",
  TAXFEE: "$TaxFee",
  USERGROUPID: "$UserGroupId",
  LEVELNAME: "$LevelName",
  RESULT: "$Result",
  ROLENAME: "$RoleName",
  LEVELID: "$LevelId",
  CHANNEL: "$Channel",
  SCORE: "$Score",
  SEARCHKEYWORDS: "$SearchKeywords",
  CONTENTTYPE: "$ContentType",
  ACHIEVEMENTID: "$AchievementId",
  FLIGHTNO: "$FlightNo",
  POSITIONID: "$PositionId",
  PRODUCTLIST: "$ProductList",
  ACOUNTTYPE: "$AcountType",
  OCCURREDTIME: "$OccurredTime",
  EVTRESULT: "$EvtResult",
  PREVLEVEL: "$PrevLevel",
  CURRVLEVEL: "$CurrvLevel",
  VOUCHERS: "$Vouchers",
  MATERIALSLOTTYPE: "$MaterialSlotType",
  LISTID: "$ListId",
  FILTERS: "$Filters",
  SORTS: "$Sorts",
  ORDERID: "$OrderId",
  PAYTYPE: "$PayType",
  REASON: "$Reason",
  EXPIREDATE: "$ExpireDate",
  VOUCHERTYPE: "$VoucherType",
  SERVICETYPE: "$ServiceType",
  DETAILS: "$Details",
  COMMENTTYPE: "$CommentType",
  REGISTMETHOD: "$RegistMethod",
  DURATION: "$Duration",
  LEVEL: "$Level",
  PURCHASEENTRY: "$PurchaseEntry",
  PROPS: "$Props",
  ENTRY: "$Entry",
  INVITER: "$Inviter",
  VIPLEVEL: "$VIPLevel",
  FIRSTSIGNIN: "$FirstSignIn",
  DISCOUNT: "$Discount",
  FIRSTPAY: "$FirstPay",
  TASKID: "$TaskId",
  FRIENDNUMBER: "$FriendNumber",
  USERGROUPNAME: "$UserGroupName",
  USERGROUPLEVEL: "$UserGroupLevel",
  MEMBERS: "$Members",
  LEVELBEFORE: "$LevelBefore",
  MESSAGETYPE: "$MessageType",
  ROLECOMBAT: "$RoleCombat",
  ISTOPLEVEL: "$IsTopLevel",
  ROLECLASS: "$RoleClass",
  SKILLNAME: "$SkillName",
  SKILLLEVEL: "$SkillLevel",
  SKILLLEVELBEFORE: "$SkillLevelBefore",
  EQUIPMENTID: "$EquipmentId",
  EQUIPMENTNAME: "$EquipmentName",
  EQUIPMENTLEVEL: "$EquipmentLevel",
  CLASSLIMIT: "$ClassLimit",
  LEVELLIMIT: "$LevelLimit",
  ISFREE: "$IsFree",
  TOTALAFTERCHANGE: "$TotalAfterChange",
  QUALITY: "$Quality",
  ENHANCETYPE: "$EnhanceType",
  NEWCLASS: "$NewClass",
  OLDCLASS: "$OldClass",
  TASKTYPE: "$TaskType",
  TASKNAME: "$TaskName",
  REWARD: "$Reward",
  ACTIVITYTYPE: "$ActivityType",
  ACTIVITYNAME: "$ActivityName",
  CUTSCENENAME: "$CutsceneName",
  PETID: "$PetId",
  PETDEFAULTNAME: "$PetDefaultName",
  PETLEVEL: "$PetLevel",
  MOUNTID: "$MountId",
  MOUNTDEFAULTNAME: "$MountDefaultName",
  MOUNTLEVEL: "$MountLevel",
  ROLEGENDER: "$RoleGender",
  SERVER: "$Server",
  FIRSTCREATE: "$FirstCreate",
  COMBAT: "$Combat",
  BATTLETYPE: "$BattleType",
  BATTLENAME: "$BattleName",
  NUMBEROFCARDS: "$NumberOfCards",
  CARDLIST: "$CardList",
  PARTICIPANTS: "$Participants",
  DIFFICULTY: "$Difficulty",
  MVP: "$MVP",
  DAMAGE: "$Damage",
  RANKING: "$Ranking",
  DUNGEONNAME: "$DungeonName",
  WINREASON: "$WinReason",
  BALANCE: "$Balance",
  PACKAGETYPE: "$PackageType",
  AMOUNT: "$Amount",
  ITEMLIST: "$ItemList",
  GIFTTYPE: "$GiftType",
  GIFTNAME: "$GiftName",
  TYPE: "$Type",
  OLDVALUE: "$OldValue",
  NEWVALUE: "$NewValue",
  VIDEOTYPE: "$VideoType",
  VIDEONAME: "$VideoName",
  MESSAGETITLE: "$MessageTitle",
  OPERATION: "$Operation",
  NUMBEROFDRAWING: "$NumberOfDrawing",
  LEFTPULLSFORGUARANTEE: "$LeftPullsForGuarantee",
  VIPTYPE : "$VipType",
  VIPSTATUS : "$VipStatus",
  VIPEXPIREDATE : "$VipExpireDate",
  ENTER : "$Enter",
  STARTDATE : "$StartDate",
  EFFECTIVETIME : "$EffectiveTime",
  NAME : "$Name",
  MODE : "$Mode",
  SUBJECT : "$Subject",
  ACCURACY : "$Accuracy",
  CONTENTLENGTH : "$ContentLength",
  REMARK : "$Remark",
  CONTENTNAME : "$ContentName",
  SECTION : "$Section",
  DAYS : "$Days",
  POSTID : "$PostId",
  INFORMATIONTYPE : "$InformationType",
  INFORMATION : "$Information",
  FEATURE : "$Feature",
  ROOMS : "$Rooms",
  SALEPRICE : "$SalerPrice",
  RENTFEE : "$RentFee",
  RENTTYPE : "$RentType",
  SERIES : "$Series",
  MODEL : "$Model",
  DEVICETYPE : "$DeviceType",
  DEVICENAME : "$DeviceName",
  BINDDURATION : "$BindDuration",
  DEALERNAME : "$DealerName",
  ARRIVALDATE : "$ArrivalDate",
  OCCURREDDATE : "$Occurredate",
  BUYERTYPE : "$BuyerType",
  SEAT : "$Seat",
  ENERGY : "$Energy",
  CONFIGURATION : "$Configuration",
  ISLOAN : "$IsLoan",
  LOANPRODUCTNAME : "$LoanProductName",
  LOANCHANNEL : "$LoanChannel",
  REPAYMENTMETHOD : "$RepaymentMethod"
};

Object.freeze(HAParamType)

export default HAParamType;
